# -*- coding: utf-8 -*-
"""Statistics_Basics_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwVuikVq7gcqEuFxSO25DJjhLdXqSR6g

### 1. Types of Data
**Qualitative Data**: Non-numeric, categorical.  
- Nominal: No natural order (e.g., gender, colors).  
- Ordinal: Ordered categories (e.g., education level).

**Quantitative Data**: Numeric data.  
- Interval: No true zero (e.g., temperature in Celsius).  
- Ratio: Has true zero (e.g., weight, height).

### 2. Measures of Central Tendency
- **Mean**: Average, used for symmetric distributions.
- **Median**: Middle value, used for skewed distributions.
- **Mode**: Most frequent value, used for categorical data.

### 3. Dispersion
- **Variance**: Average squared deviation from mean.
- **Standard Deviation**: Square root of variance, same units as data.
- Both measure data spread around mean.

### 4. Box Plot
A graphical summary using five-number summary: min, Q1, median, Q3, max.  
It helps detect skewness and outliers.

### 5. Random Sampling
Random sampling gives every individual in the population an equal chance to be selected, ensuring unbiased representation for statistical inference.

### 6. Skewness
- **Positive Skew**: Tail on the right.
- **Negative Skew**: Tail on the left.
- Affects how mean, median, and mode relate.

### 7. Interquartile Range (IQR)
IQR = Q3 - Q1.  
Used to detect outliers:  
Outliers < Q1 - 1.5*IQR or > Q3 + 1.5*IQR.

### 8. Binomial Distribution
Used when:
1. Fixed number of trials
2. Only two outcomes (success/failure)
3. Constant probability
4. Independent trials

### 9. Normal Distribution & Empirical Rule
Symmetrical, bell-shaped curve.  
Mean = Median = Mode.

**Empirical Rule**:  
- 68% within 1 SD  
- 95% within 2 SD  
- 99.7% within 3 SD

### 10. Poisson Process
Example: Number of emails per hour.  
λ = 5 emails/hour  
P(X=3) = (e^-5 * 5^3)/3! ≈ 0.1404

### 11. Random Variables
- **Random Variable**: Takes values based on outcomes of a random phenomenon.  
- **Discrete**: Countable (e.g., dice rolls).  
- **Continuous**: Measurable (e.g., weight).

### 12. Covariance and Correlation
Let's use Python to calculate these:
"""

import pandas as pd

# Example dataset
data = {
    'X': [2, 4, 6, 8, 10],
    'Y': [1, 3, 4, 6, 8]
}

df = pd.DataFrame(data)

# Covariance
covariance = df['X'].cov(df['Y'])

# Correlation
correlation = df['X'].corr(df['Y'])

print("Covariance:", covariance)
print("Correlation:", correlation)